sensor:
    - platform: adc
      id: source_sensor
      pin: GPIO33
      name: ADC
      attenuation: 11db
      internal: true

      # It is important to have a low update interval so that
      # the measurement has time to be done correctly during
      # the activation of the voltage AND taking into account the median filter
      update_interval: 250ms

      filters:
          - multiply: 0.846153 # 3.9 (11db attenuation full-scale voltage) -> 3.3V
          - median:
                window_size: 7
                send_every: 4
                send_first_at: 3

    - platform: resistance
      sensor: source_sensor
      id: real_resistance_sensor
      #name: "${friendly_name} resistance"
      configuration: DOWNSTREAM
      resistor: $resistor_value
      reference_voltage: 3.3V
      internal: true
      icon: "mdi:omega"
      filters:
          - lambda: "return max((float)$min_resistance, x);"
          - lambda: "return min((float)$max_resistance, x);"
      on_value:
          then:
              - if:
                    condition:
                        lambda: |-
                            return (
                                id(real_resistance_sensor).state > $min_resistance
                                &&
                                id(real_resistance_sensor).state <= $max_resistance
                            );
                    then:
                        - sensor.template.publish:
                              id: resistance_sensor
                              state: !lambda "return id(real_resistance_sensor).state;"

switch:
    - platform: gpio
      id: resistance_bias
      name: "${friendly_name} resistance bias"
      icon: "mdi:power"
      pin:
          number: GPIO19
          mode: OUTPUT
