# A package for Home Assistant.
# Put in packages/ folder

#code mostly borrowed from: https://github.com/devjklein/esphome-weatherstation/blob/main/sensors.yaml

#################################################################
## Sensors
#################################################################
sensor:
  - platform: statistics
    name: Meteo Tenda Raffica 10m
    entity_id: sensor.meteotendasole_vento_ms
    unique_id: sensor.meteo_tenda_raffica_10m
    state_characteristic: value_max
    sampling_size: 9999
    keep_last_sample: true
    precision: 1
    max_age:
      minutes: 10
  - platform: statistics
    name: Meteo Tenda Raffica 1h
    entity_id: sensor.meteotendasole_vento_ms
    unique_id: sensor.meteo_tenda_raffica_1h
    state_characteristic: value_max
    sampling_size: 9999
    keep_last_sample: true
    precision: 1
    max_age:
      hours: 1
  - platform: statistics
    name: Meteo Tenda Raffica 24h
    entity_id: sensor.meteotendasole_vento_ms
    unique_id: sensor.meteo_tenda_raffica_24h
    state_characteristic: value_max
    sampling_size: 9999
    keep_last_sample: true
    precision: 1
    max_age:
      hours: 24

  - platform: statistics
    name: Meteo Tenda Vento Media 1h 
    entity_id: sensor.meteotendasole_vento_ms
    unique_id: sensor.meteo_tenda_vento_1h
    state_characteristic: average_linear
    sampling_size: 9999
    keep_last_sample: true
    precision: 1
    max_age:
      hours: 1
  - platform: statistics
    name: Meteo Tenda Vento Media 10m
    entity_id: sensor.meteotendasole_vento_ms
    unique_id: sensor.meteo_tenda_vento_10m
    state_characteristic: average_linear
    sampling_size: 9999
    precision: 1
    max_age:
      minutes: 10

  - platform: statistics
    name: Meteo Tenda Pioggia Ultima ora (conteggio)
    unique_id: sensor.meteo_tenda_pioggia_ultima_ora_conteggio
    entity_id: sensor.meteotendasole_pioggia_totale_dalluptime
    state_characteristic: count
    keep_last_sample: false
    sampling_size: 999
    precision: 4
    max_age:
      hours: 1
  - platform: statistics
    name: Meteo Tenda Pioggia Ultime 24 Ore (conteggio)
    unique_id: sensor.sensor.meteo_tenda_pioggia_ultime_24_ore_conteggio
    entity_id: sensor.meteotendasole_pioggia_totale_dalluptime
    state_characteristic: count
    keep_last_sample: false
    sampling_size: 999
    precision: 4
    max_age:
      hours: 24

#################################################################
## Templates
#################################################################

template: 
  - sensor:
    - name: Meteo Tenda Pioggia Ultima ora 
      icon: mdi:beaker-outline
      unit_of_measurement: mm
      state_class: total_increasing
      unique_id: roof_rainfall_last_hour
      state: >-
        {% set count = states('sensor.meteo_tenda_pioggia_ultima_ora_conteggio') | int(0) %}
        {% set in = count * 0.30303 %}
        {% if count >= 0 %}
          {{in|round(4, 'floor') }}
        {% endif %}
        
    - name: Meteo Tenda Pioggia Ultime 24 Ore
      icon: mdi:beaker-outline
      unit_of_measurement: mm
      state_class: total_increasing
      unique_id: roof_rainfall_last_24_hours
      state: >-
        {% set count = states('sensor.meteo_tenda_pioggia_ultime_24_ore_conteggio') | int(0) %}
        {% set in = count * 0.30303 %}
        {% if count >= 0 %}
          {{in|round(4, 'floor') }}
        {% endif %}